### ISSUE TITLE
config文件

### ISSUE THREAD

**Issue by aShelby-L** [VM-Chinese-translate-group/dawncraft-Chinese-patch-Pack#15]
config文件里面，有个将config文件放在此处，是将游戏里的放进去还是将汉化文件里的放进去？？

**Comment by nageih** [comment]
此次为vm汉化组汉化dawncraft自用的库，下载汉化请前往：https://www.bilibili.com/read/cv22580986

**Comment by nageih** [comment]
@aShelby-L
