### ISSUE TITLE
snbt 里的布尔值都带上引号了

### ISSUE THREAD

**Issue by SettingDust** [VM-Chinese-translate-group/dawncraft-Chinese-patch-Pack#31]
https://github.com/VM-Chinese-translate-group/dawncraft-Chinese-patch-Pack/blob/1.18.x/zh-CN/config/ftbquests/quests/chapters/a_little_help.snbt#L9C2-L9C31
https://github.com/VM-Chinese-translate-group/dawncraft-Chinese-patch-Pack/blame/4f2d4fbf9c9a067080524cde9ebfa300552e11ab/zh-CN/config/ftbquests/quests/chapters/a_little_help.snbt#L9

**Comment by SettingDust** [comment]
https://github.com/VM-Chinese-translate-group/dawncraft-Chinese-patch-Pack/blob/1.18.x/zh-CN/global_packs/required_data/DawnCraft_Datapack/data/quest_giver/quests/quest_0001/quest_0001_03.json#L35 还有这行 lore 的汉化丢了，以前有
![图片](https://github.com/VM-Chinese-translate-group/dawncraft-Chinese-patch-Pack/assets/19922286/5a628a54-5779-43e1-8757-59359ed5e034)

**Comment by nageih** [comment]
是[FTBQLocalizationTools](https://github.com/XDawned/FTBQLocalizationTools)的问题，不过作者本人说不影响游戏内读取
漏译内容下个版本更新会补上，crowdin上搞的，给忘了

**Comment by nageih** [comment]
抱歉刚才经过测试，似乎是影响游戏内读取，目前最新版已经修复。
另外那个漏译我还是忘了更新，下个版本再更新吧，也不是很重要的内容，主要是我们用的crowdin导致工作流比较复杂，合完pr还有别的事
